### ISSUE TITLE
Identity production checklist

### ISSUE THREAD

**Issue by brandur** [heroku/identity#10]
- [x] Set up a high-fidelity staging replica. _note: see "installations" in README_
- [x] Add to the [platform lifecycle board](https://trello.com/board/platform-engineering-life-cycle/504fbaecbc351ac46c476027)
- [ ] Request an audit by the security team - this may be backlogged or handled immediately. _note: sitting down with Tom on this one tomorrow_
- [x] Has a Readme that explains how to run the app locally and create a personal platform deploy.
- [x] Has operational docs that provide executable instructions for common operational tasks.
- [x] Alerts a human if it is down. _note: see "api: identity" on Watchtower_
- [x] Has its code on Github in the Heroku organization.
- [x] Has undergone simulation testing to ensure graceful handling of degredation and failure modes. _note: api failure will result in an "internal server error" page; not the most graceful possible failure, but we can't do much better than that based on the nature of the product_
- [x] Uses [structured logging](https://github.com/heroku/engineering-docs/blob/master/logs-as-data.md).
- [x] Minimizes external service dependencies (e.g. using an existing Postgres database instead of Redis for OpenId).
- [x] Enforces SSL access (redirects all http: over to https:).
- [x] Consider adding the app to the credroll list on the
  [employee exit checklist](https://docs.google.com/a/heroku.com/spreadsheet/ccc?key=0AqLn4J8Q7We2dGR6LVFhVHNjNjlPRkxZRE4tLTlDTnc#gid=0). _note: stores no credentials so this isn't needed_
- [x] Follows our [availability best practices](https://devcenter.heroku.com/articles/maximizing-availability) with [heroku-production-check](https://github.com/heroku/heroku-production-check).
- [x] Does not depend on any development-level add-ons.
- [x] Does not have an unused add-ons installed.
- [x] Has an `ERROR_PAGE_URL` (if a web app). _note: reusing Dashboard's for now_
- [x] Has a `MAINTENANCE_PAGE_URL` (if a web app). _note: reusing Dashboard's for now_
- [x] Has been reviewed for [OWASP top-10 app vulnerabilities](https://www.owasp.org/index.php/Top_10_2010-Main).
- [x] Is owned by a Heroku Manager org. _note: owned by heroku@herokumanager.org_
- [x] Shows a suitable error page when encountering an internal error.
- [x] Has proper credentials (e.g. is not using your personal API key)
- [x] Drains app logs somewhere (e.g. splunk). _note: goes to Splunk, search app=identity_
